jdnotes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('entries/', include('notes.urls', namespace='entries')),
    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/urls.py
from django.urls import path
from .views import (
    entry_list,
    entry_detail,
    entry_create,
    entry_update,
    entry_delete
)


app_name = 'notes'
urlpatterns = [
    path('', entry_list, name='entry-list'),
    path('create/', entry_create, name="entry-create"),
    path('<int:id>/', entry_detail, name="entry-detail"),
    path('<int:id>/update/', entry_update, name="entry-update"),
    path('<int:id>/delete/', entry_delete, name="entry-delete"),

]

notes/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Entry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    description = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)  # moment it's added
    updated = models.DateTimeField(auto_now=True)  # moment it's updated
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return '/entries/{0}/'.format(self.id)

    def get_update_url(self):
        return '/entries/{0}/update/'.format(self.id)

    def get_delete_url(self):
        return '/entries/{0}/delete/'.format(self.id)

notes/forms.py
from django import forms
from .models import Entry

class EntryForm(forms.Form):
    title = forms.CharField()
    description = forms.CharField()
    image = forms.ImageField()


'''
class EntryModelForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['title', 'description', 'image']
'''

notes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Entry
from .forms import EntryForm
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
# Create your views here.

@login_required
def entry_list(request):
    entries = Entry.objects.filter(user=request.user)
    query = request.GET.get('q')
    if query:
        entries = entries.filter(
                    Q(title__icontains=query)|
                    Q(description__icontains=query)
                    ).distinct()
    context = {
        'object_list': entries
    }
    return render(request, 'notes/entries.html', context)

@login_required
def entry_detail(request, id):
    note = get_object_or_404(Entry, id=id)
    context = {
        'object': note
    }
    return render(request, 'notes/entries_detail.html', context)

@login_required
def entry_create(request):
    form = EntryForm(request.POST or None, request.FILES or None)
    if form.is_valid():

        title = request.POST.get('title')
        description = request.POST.get('description')
        image = request.FILES.get('image')

        entry = Entry()
        entry.title = title
        entry.description = description
        entry.image = image
        entry.user = request.user
        entry.save()

        #For the model form
        # form.instance.user = request.user
        # form.save()
        # entry_id = form.instance.id
        # entry = get_object_or_404(Entry, id=entry_id)
        messages.info(request, 'Created a New Note.')
        return redirect(entry.get_absolute_url())
    context = {
        'form': form
    }

    return render(request, 'notes/entries_create.html', context)

@login_required
def entry_update(request, id):
    instance = get_object_or_404(Entry, id=id)
    form = EntryForm(request.POST or None,
                          request.FILES or None, instance=instance)
    if form.is_valid():
        form.save()
        entry_id = form.instance.id
        entry = get_object_or_404(Entry, id=entry_id)
        messages.info(request, 'Successfully Updated the Note.')
        return redirect(entry.get_absolute_url())
    context = {
        'form': form,
        'instance': 'object',
    }

    return render(request, 'notes/entries_update.html', context)

@login_required
def entry_delete(request, id):
    entry = get_object_or_404(Entry, id=id)
    if entry.user != request.user:
        response = HttpResponse(
            "You don't have permission to delete this note.")
        response.status_code = 403
        return response
    if request.method == 'POST':
        entry.delete()
        messages.info(request, "This note has been successfully deleted.")
        return redirect("/entries/")
    context = {
        'object': entry
    }
    return render(request, "notes/entries_delete.html", context)

notes/templates/notes/entries.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <h1>My Entries</h1>
      <table class="table">
        {% for object in object_list %}
        <p><a href="{{ object.get_absolute_url }}">{{ object.title }}</a> - {{ object.timestamp|timesince }} ago</p>
        <hr> {% endfor %}
      </table>
    </div>
  </div>
</div>

{% endblock %}

notes/templates/notes/entries_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <h1>Create a New Note</h1>
      {% include 'form.html' %}
    </div>

  </div>
</div>

{% endblock %}

notes/templates/notes/entries_delete.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <h3>Are you sure you want to delete this note?</h3>
      <form method="post" action=".">
        {% csrf_token %}
        <input type="submit" name="submit" class="btn btn-default" placeholder="Delete">
      </form>
    </div>
  </div>
</div>

{% endblock %}

notes/templates/notes/entries_detail.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <div class="thumbnail">
        <img src="{{ object.image.url }}" class='img-fluid'>
      </div>

      <h1>{{ object.title }} <small>{{ object.timestamp|timesince }} ago</small></h1>
      <p>{{ object.description }}</p>
      <p>Last Updated: {{ object.updated }}</p>
      <a href="{{ object.get_update_url }}">Update Now</a>
      <a href="{{ object.get_delete_url }}">Delete This Note</a>
    </div>
  </div>
</div>

{% endblock %}

notes/templates/notes/entries_update.html
{% extends 'base.html' %} {% block content %} {% load crispy_forms_tags %}
<div class="container">
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6">
      <h1>Edit Note</h1>
      <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ form|crispy }}
        <input type="submit" name="submit" class="btn btn-default" placeholder="submit">
        <button class="btn btn-default"><a href="{{ object.get_absolute_url }}"></a>Cancel</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  {% load staticfiles %}
  <meta charset="utf-8">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
  <title></title>
</head>

<body>

  {% include 'navbar.html' %} {% if messages %}
  <div class="alert alert-success alert-dismissible fade show container-alert" role="alert">
    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
      {% endfor %}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>



  {% endif %} {% block content %} {% endblock %}


  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>

templates/form.html
<form class='form' method='POST' action='/entries/create/' enctype="multipart/form-data">
			   	{% csrf_token %}
                        <div class='form-group'>
                            <input type='text' class='form-control' name='title' placeholder='Title' />
                        </div>
                        <div class='form-group'>
                            <input type='text' class='form-control' name='description' placeholder='Description' />
                        </div>
                        <div class='form-group'>
                            <input type='file' class='form-control' name='image' />
                        </div>
                        <input type="submit" name="submit" class="btn btn-default" placeholder="Submit">
                      </form>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'notes:entry-list' %}">Notes</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'entries:entry-create' %}">Create</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'entries:entry-list' %}">My Notepad</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link disabled" href="/accounts/logout/">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="/accounts/signup/">Sign Up</a>
      </li>

      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>